version: '3.4'

services:

    imageSquash:
       restart: "no"
       image: imagine10255/bear-imagemin-api:0.0.5
       ports:
         - "3002:3000"

networks:
    default:
        external:
            name: imdockgroup
